apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "robot-shop-app"
  labels:
    app.kubernetes.io/name: "robot-shop-app"
    app.kubernetes.io/version: "1.0.0"
spec:
  selector:
    matchLabels:
     app.kubernetes.io/name: "robot-shop-app"
  descriptor:
    links:
      - description: "Open Robot Shop"
        url: http://web